### ISSUE TITLE
Error procesing update.

### ISSUE THREAD

**Issue by 3navis** [DarkWanderer/Elite-Log-Agent#24]
![error](https://user-images.githubusercontent.com/37496617/43043959-4ac3b3b0-8d9d-11e8-86ad-81ba2ce07f5e.JPG)

**Comment by DarkWanderer** [comment]
Thank you for your report.

Looks like Json.Net can't parse Statistics event for some reason. Would you be able to attach (or send me privately) a couple of latest E:D log files, so I can take a closer look?

**Comment by DarkWanderer** [comment]
Thank you for your report.

Looks like Json.Net can't parse Statistics event for some reason. Would you be able to attach (or send me privately) a couple of latest E:D log files, so I can take a closer look?

**Comment by YinYin-Falcon** [comment]
Similar problem here:

![image](https://user-images.githubusercontent.com/3826749/44274062-81429b00-a241-11e8-8d9f-23b97d5a9e02.png)

5 latest logs:

[Journal.180812130523.01.log](https://github.com/DarkWanderer/Elite-Log-Agent/files/2297771/Journal.180812130523.01.log)
[Journal.180726183818.01.log](https://github.com/DarkWanderer/Elite-Log-Agent/files/2297772/Journal.180726183818.01.log)
[Journal.180723150336.01.log](https://github.com/DarkWanderer/Elite-Log-Agent/files/2297773/Journal.180723150336.01.log)
[Journal.180521153811.01.log](https://github.com/DarkWanderer/Elite-Log-Agent/files/2297774/Journal.180521153811.01.log)
[Journal.180817124009.01.log](https://github.com/DarkWanderer/Elite-Log-Agent/files/2297775/Journal.180817124009.01.log)

**Comment by DarkWanderer** [comment]
Hi @YinYin-Falcon,

Thanks for your report and especially for attached files. I'm in a trip until this weekend but will definitely take a look then.

Note it seems to be a different root cause than the error in OP, but definitely needs fixing too.

**Comment by DarkWanderer** [comment]
@YinYin-Falcon current release contains a few improvements around data parsing - please let me know if that helped

**Comment by YinYin-Falcon** [comment]
Nope, I'm getting the exact same error.

**Comment by DarkWanderer** [comment]
Hi. Thank you very much for your reports.

Curiously, I cannot reproduce this at all. The journal files are well-formed and are parsed without issues or exceptions. I have tried switching locale, but that didn't help a little bit - everything still parses fine. 

There must be something I am missing when trying to reproduce. It's almost as if something is changing the file at the same time the program tries to read it. Do you guys run EliteLogAgent in parallel with other log-parsing software?

**Comment by YinYin-Falcon** [comment]
No, I didn't even run E:D when I tested this.
I'm not getting errors on the current build anymore.
(I've got new logs since last time)

But I also don't see any logs appearing on EDSM after clicking upload.

And the API key validates successfully with the wrong combat rank (mostly harmless).

**Comment by DarkWanderer** [comment]
Great - sounds like the original error is fixed then.

As for EDSM, if the server returns a combat rank (event mostly harmless), it means that the API key is correct (but for wrong account?). Can you try:

1. Regenerating API key & putting it into the app
2. Restarting the app (just in case)
3. Pressing "import latest data"
4. Waiting for 90 seconds
5. Opening EDSM and checking for data?

That should account for both load-reducing mechanisms triggering and potentially incorrect key

If that fails - please attach ELA log (%appdata%\EliteLogAgent\Log), I'll take a closer look

**Comment by DarkWanderer** [comment]
@3navis does the issue reproduce for you in latest release?

**Comment by 3navis** [comment]
yes, release is 6.3.282

Validate EDSM return Success, combat rank: Dangerous
Validate INARA return Success, Inara ID: 62505
Upload last 5 files, Error ,,,, line 12 position 1839

Can I know exactly what file he is trying to read?
regards,

**Comment by DarkWanderer** [comment]
The "import latest" function takes 5 last .log files sorted by name, plus whatever is in .json files (commodities, outfitting, shipyard etc.). The data is taken from "saved games" Windows dir - usually it's `C:\Users\<username>\Saved Games\Frontier Developments\Elite Dangerous`.

Can you zip the whole log dir? That'd be easier to look at (I'll delete it afterwards)

**Comment by 3navis** [comment]
Hello,
thank you very much for the information.
when I have ordered by name they have appeared log files of the Beta, in front of the correct ones.
     "Journal**Beta**.180126075403.01.log" (7 files)
I have removed these files and the problem has been solved,

**Comment by DarkWanderer** [comment]
@YinYin-Falcon That is what I meant, sorry for not being clear. Yes, JournalBeta are likely causing the issue here. No need to delete JournalBeta files, I will fix them in scope of #35. ETA this weekend.

**Comment by DarkWanderer** [comment]
@YinYin-Falcon Latest [release](https://github.com/DarkWanderer/Elite-Log-Agent/releases/tag/release-0.6.3.294) should be working fine with JournalBeta files present. Could you please confirm?

**Comment by YinYin-Falcon** [comment]
Can confrim.

Is there a way to upload more than the last 5 logs? There is a bit of a gap for me.

**Comment by DarkWanderer** [comment]
Splendid - thanks for the help in debugging to both of you.

> Is there a way to upload more than the last 5 logs?

There is no way in the program itself at the moment. You can go one of following ways:

- Manually import logs to Inara/EDSM (EDSM supports bulk upload, Inara - manual file-by-file)
- Move last x (say, 50) journal files to another directory and go with a loop: "import latest" => move back 5 oldest files => "import latest" => etc.

I will think about allowing a wider range in the app itself - need to make sure it's not abused
