### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by phelbore** [DarkWanderer/Elite-Log-Agent#25]
Can you include a changelog or link to a changelog when it updates?

**Comment by DarkWanderer** [comment]
Will think about it. I won't have the patience to maintain a manual one - will devise something (semi-)automatic

**Comment by DarkWanderer** [comment]
Created a [wiki page](../wiki/Changelog) for changelog

**Comment by DarkWanderer** [comment]
Thanks for feedback!
