### ISSUE TITLE
Start Menu Folder

### ISSUE THREAD

**Issue by phelbore** [DarkWanderer/Elite-Log-Agent#26]
The start menu folder is CMDR John Kozak.  Elite Log Agent would be a lot more clear.

**Comment by DarkWanderer** [comment]
Start menu folder will be changed in next update - to "Elite Log Agent". After update, please check autorun - it may break & become disabled as it depends on start menu item. In worst case, can always reinstall the app (settings are preserved)

**Comment by DarkWanderer** [comment]
Released & checked - works on my machine (tm), but please give me a shout if something breaks for you
