### ISSUE TITLE
Allow to import wider range of historic data

### ISSUE THREAD

**Issue by DarkWanderer** [DarkWanderer/Elite-Log-Agent#36]
As per discussion in #24, it would be beneficial to be able to import more than 5 historic files. Following needs to be taken into consideration:

- Inara only accepts events which are less than 1 month old
- This could potentially abused to DoS the target sites - need to add mechanism to prevent that

**Comment by YinYin-Falcon** [comment]
Do the APIs support querying their latest entry so you can upload logs from there onwards?

**Comment by YinYin-Falcon** [comment]
I'm only using edsm and have bulk uploaded there before.

**Comment by DarkWanderer** [comment]
You should be able to just drag & drop a set of files to EDSM then - that should cover your gap. And ELA will keep data updated as you go from there.

**Comment by DarkWanderer** [comment]
"Historic import" feature removed - INARA supports import from Frontier now, and EDSM supports drag-and-drop from file system
