### ISSUE TITLE
Multiple CMDR support

### ISSUE THREAD

**Issue by DarkWanderer** [DarkWanderer/Elite-Log-Agent#37]
Possible implementation:

- Scan the file from the beginning on start 
- Detect commander name from the begginning of file rather than from setting
- (???) feed the on-startup events into plugins (assuming a sane person won't restart the app again and again when the game is launched)
- Attach the commander name as 'context' to each event
- Have multiple profiles inside each CMDR-dependent plugin with specific profile being pulled by cmdr name

**Comment by 3navis** [comment]
Hello,
Is this error (mix second CMDR) fixed in the current version?
![error multicuenta](https://user-images.githubusercontent.com/37496617/53714884-5a9c2880-3e50-11e9-96bf-4d2d5bc0c347.JPG)

**Comment by DarkWanderer** [comment]
Multiple commanders are not supported yet, sorry. You can delete "bad" records in INARA, by the way

**Comment by 3navis** [comment]
ok, thanks

**Comment by jakaarl** [comment]
This would be lovely, I just created my second account. And yes, it does mess up Inara. I was expecting Steam and "standalone" to be separate enough, so E.L.A. wouldn't pick up my Steam activity, but I was wrong. Naturally, a multi-CMDR setup would also need to support multiple API keys.

**Comment by DarkWanderer** [comment]
[Dev build](https://ci.appveyor.com/api/buildjobs/skg4pkdbu3f3ly2i/artifacts/ELA.Portable.1.2.0.576.zip) available - API key validation does not work in the UI, but it's not required. If anyone's willing to test it out, that'd be appreciated

**Comment by DarkWanderer** [comment]
Released in 1.3.0.597
