### ISSUE TITLE
No INARA entry in settings in latest version

### ISSUE THREAD

**Issue by NikolaiVChr** [DarkWanderer/Elite-Log-Agent#61]
In latest windows version I see no way to input INARA key in settings.

How do I do that?

![image](https://user-images.githubusercontent.com/3764194/50114006-cdc7d280-0243-11e9-8b7b-460b61916c3c.png)

**Comment by puchuchoni** [comment]
Can confirm that this has been happening to me too with the latest portable version released.

![image](https://user-images.githubusercontent.com/28080765/50133642-265e9600-026b-11e9-9f4c-8e872b5488ff.png)

**Comment by DarkWanderer** [comment]
Release [0.9.2.412](https://github.com/DarkWanderer/Elite-Log-Agent/releases/tag/release-0.9.2.412) is out which fixes the issue - please let me know if you still experience issues
