### ISSUE TITLE
Error in uploading last 5 journals

### ISSUE THREAD

**Issue by NikolaiVChr** [DarkWanderer/Elite-Log-Agent#63]
I got a mission now on INARA that says:

Clothing seeks sightseeing adventure
For Future of Arro Naga
Origin: Shinrarta Dezhra [Jameson Memorial]
Destination: Wolf 497
 
Influence gain: +

I did source him 3 clothing, but it clearly was not clothing that gave me the mission.

Thanks for making the program. :)

**Comment by DarkWanderer** [comment]
I have to admit I have not tested passenger missions extensively :) Thanks for reporting this, will check

**Comment by NikolaiVChr** [comment]
This is how an entry looks, notice there are multiple destinations too:

{ "timestamp":"2018-12-21T03:11:49Z", "event":"MissionCompleted", "Faction":"Los Chupacabras", "Name":"Mission_Sightseeing_name", "MissionID":442949477, "Commodity":"$Clothing_Name;", "Commodity_Localised":"Clothing", "Count":3, "NewDestinationSystem":"Shinrarta Dezhra", "DestinationSystem":"LHS 3675$MISSIONUTIL_MULTIPLE_INNER_SEPARATOR;Hecate$MISSIONUTIL_MULTIPLE_INNER_SEPARATOR;Tujing$MISSIONUTIL_MULTIPLE_FINAL_SEPARATOR;HIP 57822", "Reward":4978600, "FactionEffects":[ { "Faction":"Los Chupacabras", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_SP_up;", "Effect_Localised":"The security status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":3932277478106, "Trend":"UpGood", "Influence":"+++++" } ], "ReputationTrend":"UpGood", "Reputation":"+" } ] }

**Comment by DarkWanderer** [comment]
Fix released in 0.9.5.444
