### ISSUE TITLE
Feature request: Add SystemAddress to EDDN scans

### ISSUE THREAD

**Issue by klightspeed** [DarkWanderer/Elite-Log-Agent#72]
`FSDJump`, `Location` and `Docked` include `SystemAddress` (an `Int64`).  Would it please be possible to add it to the fields added to events that don't already have it?

**Comment by DarkWanderer** [comment]
I think I can add this. What's the use case, out of curiosity?

**Comment by klightspeed** [comment]
See the replies to your question on Sep 25 in the EDDN channel on the EDCD discord.

SystemAddress is useful for positively determining a system, even across a rename.  It is the immutable system ID for the system.

**Comment by DarkWanderer** [comment]
Noted - will push it into one of next releases

**Comment by DarkWanderer** [comment]
Released in 0.9.6.467
