### ISSUE TITLE
Change Canonn APIv2 Link

### ISSUE THREAD

**Issue by derrickmehaffy** [DarkWanderer/Elite-Log-Agent#8]
Hello,

Here is a link to our API that is in development, currently is it not pushed live for public use, but wanted to inform you for future reference.

https://github.com/canonn-science/CAPIv2-Strapi

Eventually when pushed to live, it will reside here: https://api.canonn.tech

Thanks!

**Comment by DarkWanderer** [comment]
Thanks for info Derrick! I've updated the readme and will definitely take a look at it when it's live
