### ISSUE TITLE
EDSM API key validation not working

### ISSUE THREAD

**Issue by PaulKlein** [DarkWanderer/Elite-Log-Agent#85]
I have got an API key from EDSM, but after I enter it into the log agent settings window, the validate button only says 'Message not found' and doesn't accept the API key.

I have tried regenerating the API key from EDSM but this doesn't seem to help.

Any ideas?
![edsm failure](https://user-images.githubusercontent.com/25495777/53160922-c818af80-362d-11e9-9199-7477820d1428.png)

**Comment by DarkWanderer** [comment]
@PaulKlein thanks for finding & reporting this - indeed there's an exception when the key is empty. You can work around this by pressing Win+R, copying there following string:
`notepad %appdata%\EliteLogAgent\Settings.json`
Then pasting your EDSM API key into `apiKey` parameter in following section:
```
    "EdsmUploader": {
      "apiKey": "",
      "verified": true
    }
```
I'll include a proper fix in the patch this weekend

**Comment by DarkWanderer** [comment]
@Peliia this is a separate issue - a bug in release 1.0.0. Will fix as well, thanks for reporting

**Comment by DarkWanderer** [comment]
[Release 1.0.1.518](https://github.com/DarkWanderer/Elite-Log-Agent/releases/tag/release%2F1.0.1.518) is out which should fix both issues

**Comment by PaulKlein** [comment]
@DarkWanderer Thanks so much, I've just downloaded the new version and it's working perfectly.

Thanks for your support and very helpful app!
