### ISSUE TITLE
Prompt to install missing software when starting

### ISSUE THREAD

**Issue by Voz-DeCarabas** [DarkWanderer/Elite-Log-Agent#89]
I have a new Windows 10 machine and each time the Elite Log Agent starts it prompts me to go to the store to search for a missing app that is needed.  I can say 'no' to that and the app still runs fine.  Any idea what it thinks is missing?

**Comment by DarkWanderer** [comment]
Hi,

ClickOnce installer checks for presence of .NET framework which the app requires (4.6). If you have a new Windows 10 machine, it probably only has 4.7, which confuses the installer. But .NET framework is compatible with older version, so it all works.

I'll see if I can painlessly update the dependency - meanwhile, would it be possible for you to attach a screenshot of the prompt? Maybe I'll add it to docs

Thanks for reporting this

**Comment by Voz-DeCarabas** [comment]
I'll sort that this evening.  I will also confirm which version(s) of the .net framework are on there.

**Comment by Voz-DeCarabas** [comment]
Here's the message I get when starting the application.
![Install Message](https://user-images.githubusercontent.com/23322189/55106956-0b9c8880-50c8-11e9-8df4-d6cccb45ba3f.png)

To confirm I only have .net 4.7.2 (based on the release code 461808 in the registry)

**Comment by DarkWanderer** [comment]
@Voz-DeCarabas thanks for info - I've pushed release 1.1.0 today which contains fix for this, among other things. Let me know if you still experience this after upgrade

**Comment by Voz-DeCarabas** [comment]
@DarkWanderer sorry but still getting the message as attached.

![Install Message 2](https://user-images.githubusercontent.com/23322189/55285777-d0c97780-5389-11e9-8959-a70e5b02f6c0.png)

**Comment by Voz-DeCarabas** [comment]
Error still occurring in 1.2.0.569

**Comment by DarkWanderer** [comment]
Planning to switch to MSIX installer in one of future versions - hopefully that will fix it. In the interim, I've heard reports that installing .NET framework 4.6.2 helps as a stopgap.

**Comment by Voz-DeCarabas** [comment]
That would be good.
I'll hopefully get chance this evening to look at .net 4.6.2 and see if that helps.

**Comment by Voz-DeCarabas** [comment]
No joy.  I can't install that version. From following the error - 
"Because the 4.x versions of the .NET Framework are in-place updates, you cannot install an earlier version of the .NET Framework 4.x on a system that already has a later version installed. For example, on a system with Windows 10 Fall Creators Update, you cannot install the .NET Framework 4.6.2, since the .NET Framework 4.7.1 is preinstalled with the operating system."

**Comment by Voz-DeCarabas** [comment]
My PC just went through a long and tedious update and the error message on start-up is no longer happening.  On the first run it prompted that it stopped the app running as it was unknown.  I told it to ignore the error and it no longer gives the error message.

this update https://support.microsoft.com/en-gb/help/4505903/windows-10-update-kb4505903

**Comment by DarkWanderer** [comment]
I've tested the current 1.3.1 version installation on a completely clean VM from Azure and it worked as well, without prompts - so I conclude it was most likely some local Windows issue
