### ISSUE TITLE
Repeating "Elite Log Agent Error"

### ISSUE THREAD

**Issue by Redstone551** [DarkWanderer/Elite-Log-Agent#90]
Session switching to farm resources, every time i log out windows pings an error saying "Elite Long Agent Error - Error while processing events". Not sure how big of a problem it is, just not sure if anyone else is having the error ping.

**Comment by DarkWanderer** [comment]
Hi. Sorry it took a long time to reply. This error is due to your INARA key not set up correctly - the logs contain the full error, but the UI only displays the "short" version of it. This will be fixed in next release

**Comment by DarkWanderer** [comment]
New version 1.3.1.606 will generate less error notifications and the text will contain actual errors - please let me know if you're still seeing error messages which are 'less than useful'
