### ISSUE TITLE
Elite Log Agent not updating INARA CMDR profile

### ISSUE THREAD

**Issue by D1Z4STR** [DarkWanderer/Elite-Log-Agent#94]
I cannot for the life of me get the program to work. API key has been set and after playing the game and refreshing my Commander section on INARA nothing happens. Any ideas?

**Comment by DarkWanderer** [comment]
Greetings! Couple of things I'd suggest to check:
1. If you open settings, INARA section, and click "Validate" - does the API key highlight in green?
2. Do you start the game *after* app has been started?

**Comment by D1Z4STR** [comment]
Good day DarkWanderer,

1. Yes it does, when I boot up the program or come back to that screen it does not stay green. Is it always supposed to be green all the time?
2. I am testing by running the game first then opening the app. I will travel to another system to see if I get any update and refresh my CMDR page on INARA. Still shows nothing (no credits, no ships, pledge)

**Comment by D1Z4STR** [comment]
Test complete - Need to run agent before starting game

**Comment by DarkWanderer** [comment]
Yes, indeed. Currently, you do need to start agent before the game (may change that later). 

As for badges, some INARA data (badges, global 'score') can only be updated using Frontier data import - to prevent 'cheating' using API. Naturally they won't work if that import doesn't work (which is probably the case with 'keyless' accounts)
