### ISSUE TITLE
Text log of processed events

### ISSUE THREAD

**Issue by BloodyRain2k** [DarkWanderer/Elite-Log-Agent#95]
I just downloaded the app and linked it to my Inara key and played a round.
According to Inara the app uploaded 4x 2 events since I installed it, but nothing updated on their end.

Now I'm at a loss of what's not working and I have no idea how to find out.

Couldn't the general tab have a log of stuff the app has done, so one can check if things are working correctly?

**Comment by DarkWanderer** [comment]
Greetings. Have you checked the [application logs](https://github.com/DarkWanderer/Elite-Log-Agent/wiki/Troubleshooting#how-to-find-logs) - are there any problems highlighted there?

**Comment by BloodyRain2k** [comment]
I've found the issue by now, and the logs too, but both weren't obvious.

Regarding the logs: the error messages are exactly what I meant, just that they should also be displayed in the program, maybe in a tree view since they're json blocks after all.
But the files weren't where the linked page said they'd be. Instead they're sitting next to the .exe in a subfolder named "Logs".


And the initial issue was that I entered my Inara account name instead of my commander's name, which at the time made sense to me, as it was Inara's API key next to it.
But looking through the error logs it's more logical that the program needs the commander's name to know what entries to parse.

So the uploading seems to work more or less now.
I think... There's still some "unknown commander" errors which I'm not sure how they happen.

**Comment by DarkWanderer** [comment]
> But the files weren't where the linked page said they'd be. Instead they're sitting next to the .exe in a subfolder named "Logs".

That is covered in the docs: `Logs of portable version are written at same location as the app`. I've added clarification that portable version is .zip one.

> And the initial issue was that I entered my Inara account name instead of my commander's name, which at the time made sense to me, as it was Inara's API key next to it.

I think validation should have caught this issue

> I think... There's still some "unknown commander" errors which I'm not sure how they happen.

Something like this near game start time? 
`
{ 
    "level": "Info", 
    "time": "2019-09-29 12:06:24.8545", 
    "message": "Events discarded, unknown commander", 
    "logger": "DW.ELA.Plugin.EDSM.EdsmPlugin", 
    "eventsCount": 2, 
    "commander": "null" 
}
`
This is due to game issue where some events (namely, "friend online" you're logged in) are emitted before "Commander" event. These are not usually important so the app just discards them. Another thing which was broken in September update

> So the uploading seems to work more or less now.

Great, glad the issue is solved

**Comment by BloodyRain2k** [comment]
The validation might seem to have caught the name mismatch, it was orange before and now it's green.
It'd be nice to have a feedback for the error though, a label that tells "Unknown commander. Did you enter your commander's name right?" or something like that.

As for the error, it looks like this:
```
{
  "level": "Info",
  "time": "2019-09-29 00:00:14.2020",
  "message": "Events discarded, unknown commander",
  "eventsCount": 3,
  "commander": "BloodyRain2k"
}
```

**Comment by DarkWanderer** [comment]
> It'd be nice to have a feedback for the error though, a label that tells "Unknown commander. Did you enter your commander's name right?" or something like that.

I don't want the user to be annoyed by constant pop-ups, 'non-intrusiveness' is a design priority here. But will think about it

> "commander": "BloodyRain2k"

If tye commander is not null, that means CMDR was detected but you dont have an api key for him (i.e. EDSM). Will look into clarifying log message here

**Comment by BloodyRain2k** [comment]
> I don't want the user to be annoyed by constant pop-ups, 'non-intrusiveness' is a design priority here.
That's why I said a label. As in just a textfield that unhides. Like right of the buttons for example.

**Comment by DarkWanderer** [comment]
Do you have EDSM key set? These may relate to EDSM, and credit balance is only correctly updated at the start of next session

**Comment by BloodyRain2k** [comment]
Nope, I only got Inara. Do I have to get an EDSM one too now? : (

**Comment by DarkWanderer** [comment]
No, you can just ignore these messages - they only indicate that you have no EDSM key (for this particular CMDR you're playing as) and nothing is sent to EDSM. INARA upload works normally

**Comment by DarkWanderer** [comment]
Since 1.3.3, messages have been reworded and now state that CMDR api key has not been set. There's also a right-click option to open logs dir
