### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by Rfvgyhn** [DarkWanderer/Elite-Log-Agent#97]
I play the game on linux and would like to have a console based logger (which I'd be willing to write). Ideally that would be a .net core app and not need to use mono.

I see you have a .net core feature branch. Is that still in the works? Would you be interested in some help with that? Just after a cursory glance, it would seem that the libraries would need to be converted to .net standard and the gui would need to be converted to a .net core app.

**Comment by DarkWanderer** [comment]
Greetings. I've given the migration a go and it doesn't actually cause issues - but unfortunately ClickOnce which I'm using for distribution is not supported with .NET Core. This is the main blocker right now - I don't have a good alternative for it and I don't want to roll out homegrown one. [Squirrel](https://github.com/Squirrel/Squirrel.Windows/issues/1374), for example, does not support .NET Core 3.0 (which is required to support WinForms) :(

Any suggestion for an easy-to-use framework are appreciated

**Comment by Rfvgyhn** [comment]
What are your thoughts on just upgrading the libraries to .net standard and leaving the winforms app as full framework? 

Unfortunately, I'm not sure of any deployment frameworks besides Squirrel and MSIX. MSIX doesn't look nearly as friendly as Squirrel. And I assume Squirrel's option for using `Update.exe` doesn't interest you (I've never actually used either so I'm not familiar with the pros and cons).

**Comment by 3navis** [comment]
sorry i am currently not doing any programming, and i am a bit out of date.
I'm going to ask people at work if they use these tools, and I'll inform you if they tell me something interesting.
Enviado desde Correo para Windows 10

De: Chris
Enviado: miércoles, 8 de abril de 2020 2:02
Para: DarkWanderer/Elite-Log-Agent
CC: Subscribed
Asunto: Re: [DarkWanderer/Elite-Log-Agent] .Net Core (#97)

What are your thoughts on just upgrading the libraries to .net standard and leaving the winforms app as full framework?
Unfortunately, I'm not sure of any deployment frameworks besides Squirrel and MSIX. MSIX doesn't look nearly as friendly as Squirrel. And I assume Squirrel's option for using Update.exe doesn't interest you (I've never actually used either so I'm not familiar with the pros and cons).

**Comment by Rfvgyhn** [comment]
Just an FYI, I've prototyped a cross platform gui by replacing winforms with [avalonia](https://github.com/AvaloniaUI/Avalonia).

https://github.com/Rfvgyhn/Elite-Log-Agent/tree/netcore-xplat

GIF of app running on arch linux:
![ela-avalonia](https://user-images.githubusercontent.com/731861/80926648-b19fd500-8d55-11ea-9b15-7835cca3d064.gif)

**Comment by jakaarl** [comment]
ClickOnce shouldn't be a deal breaker anymore, see: https://github.com/dotnet/deployment-tools/issues/9

**Comment by DarkWanderer** [comment]
Nice, will take a look when I have spare time
