### ISSUE TITLE
INARA Api Key finnicky

### ISSUE THREAD

**Issue by DingoPlayz** [DarkWanderer/Elite-Log-Agent#98]
I've been trying to register my INARA Api Key, it previously worked but currently it's showing up red. I've completely reinstalled ELA multiple times, and checked that I'm using the right key via copy and paste and it still shows up red.

**Comment by DingoPlayz** [comment]
Seems to be off and on, it currently worked for a bit then failed once more. Maybe the API registration has a cooldown?

**Comment by DingoPlayz** [comment]
Yeah keeps being off and on, can't register my INARA API key, still doesn't work and then randomly starts working again.

**Comment by DarkWanderer** [comment]
INARA returns an error if there are too many requests in short amount of time, does it work if you leave it alone for a few minutes (with game not running) and *then* press "Validate"?
