### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Jayark365** [DarkWanderer/Elite-Log-Agent#99]
Getting a bunch of these errors. Despite my information being filled in.

{ "level": "Info", "time": "2021-02-05 02:10:34.8328", "message": "No EDSM API key set for commander, events discarded", "logger": "DW.ELA.Plugin.EDSM.EdsmPlugin", "eventsCount": 1, "commander": "null" }
{ "level": "Info", "time": "2021-02-05 02:11:34.8506", "message": "No EDSM API key set for commander, events discarded", "logger": "DW.ELA.Plugin.EDSM.EdsmPlugin", "eventsCount": 2, "commander": "null" }
{ "level": "Info", "time": "2021-02-05 02:14:34.8935", "message": "No EDSM API key set for commander, events discarded", "logger": "DW.ELA.Plugin.EDSM.EdsmPlugin", "eventsCount": 3, "commander": "null" }
{ "level": "Info", "time": "2021-02-05 02:15:04.2151", "message": "No INARA API key set for commander, events discarded", "logger": "DW.ELA.Plugin.Inara.InaraPlugin", "eventsCount": 1, "commander": "null" }

**Comment by DarkWanderer** [comment]
Hi. Have you validated the keys after inputting them? there's a "validate" button on top of thelist in both INARA and EDSM tabs

**Comment by Jayark365** [comment]
I have. Even tried running it from source. The cmdr parameter is always null. 

Was going to use your tool as a base to write a trading/exploration based overlay. But i kinda have to get it to work as intended first.

On Feb 5, 2021, at 4:30 AM, Oleg V. Kozlyuk <notifications@github.com> wrote:

﻿
Hi. Have you validated the keys after inputting them? there's a "validate" button on top of thelist in both INARA and EDSM tabs

**Comment by DarkWanderer** [comment]
Are you launching the tool after the game?

**Comment by Jayark365** [comment]
I am.

**Comment by Jayark365** [comment]
Well, I tried before and after to be more specific, same result either way.

**Comment by DarkWanderer** [comment]
You need to have the app running before you are logging in (selecting "Open"/"Private"/"Solo" etc). Also, please check that your CMDR name is correct in the app - it needs to be exactly same

You can check that by navigating to `%appdata%\..\..\Saved Games\Frontier Developments\Elite Dangerous`, opening latest log and looking for `Commander` event, e.g.:
`{ "timestamp":"2021-02-04T21:37:27Z", "event":"Commander", "FID":"F77777", "Name":"John Kozak" }`

**Comment by Jayark365** [comment]
Even the logs say cmdr is null. It's never detected. At no point is my cmdr name in the logs. Always null

**Comment by DarkWanderer** [comment]
Even in the game logs itself? I somewhat doubt it.

**Comment by Jayark365** [comment]
Oh, sorry. I misread. They read correctly in the game logs. But i dont see how that’s relevant given the program isn’t detecting a cmdr at all let alone my profile. I. E. There’s nothing for the program to compare the game logs to when it comes to getting the cmdr. If i recall. There’s an if statement that controls the cmdr set property. That If statement returns false as cmdr is null from start to finish.

On Feb 5, 2021, at 8:40 AM, Oleg V. Kozlyuk <notifications@github.com> wrote:

﻿
Even in the game logs itself? I somewhat doubt it.

**Comment by DarkWanderer** [comment]
It's relevant because the tool uses `Commander` event to detect your name, to facilitate multiple profiles support. If it's not detected, it means either:

1. you have started the tool after logging 
2. The game did not emit `Commander` event (doubtful)
3. The event has format which cannot be parsed by the tool

Can you find & paste here this event from latest log? It should be near the beginning of the file

**Comment by Jayark365** [comment]
Now that you mention the emition of the cmdr event. I recall, When working on an overlay a few weeks back, i noticed the game doesn't emit LoadGame more than once unless you stop the client and reload it, go in game and sometimes jump to a new system. Seemed to be the same for the Commander event and one other event related to system data i cant recall the name of. I kind of assumed it was intentional and didn't think much of it. But if that event never emits, or doesn't emit when it should. That'd explain the tool not working. 

I'll do some more digging when i get home to send you those logs.
